source("https://rubygems.org")

gem("sinatra")
gem("sinatra-contrib", :require => "sinatra/reloader")
gem("sinatra-activerecord", :require => "sinatra/activerecord")
gem('sinatra-flash')
gem("async_sinatra")
gem('bcrypt')
gem("rake")
gem("pg")
gem("private_pub")
gem("pry")
gem('sprockets')
gem("sequel")
gem("rack-flash3")
gem("thin")
gem("faye")
gem('require_all')
gem("sinatra-authentication", :require => "digest/sha1")

group(:test) do
  gem("rspec")
  gem("shoulda-matchers", "~> 2.0")
  gem("capybara")
end
